Update userlinks

diff --git a/sssd/assets/userlinks b/sssd/assets/userlinks
--- a/sssd/assets/userlinks
+++ b/sssd/assets/userlinks
@@ -3,7 +3,20 @@
 BASE_DIR=$SHARED_DIRECTORY
 PREFIX=$GROUP_PREFIX
 
-for DIR in $(ls -l $BASE_DIR | awk '{if ($4 != "root"){print $9;}}'); do
+
+if [ -z $1 ]; then
+
+	for DIR in $(ls -l $BASE_DIR | awk '{if ($4 != "root"){print $9;}}'); do
+		echo -n "CRON: Searching group "$PREFIX$DIR"..." 
+		/usr/bin/getent group $PREFIX$DIR > /dev/null && echo "OK" && \
+		for USER in $(/usr/bin/getent group $PREFIX$DIR | awk '{split($1,users,":"); split(users[4],user,","); for (i=1;i in user;i++) {print user[i];}}'); do
+			echo -n "      Adjusting "$USER" link to "$BASE_DIR"/"$DIR"..." && \
+			mkdir -p /home/$USER && chown $USER /home/$USER && \
+			cd /home/$USER && ln -sf $BASE_DIR/$DIR && echo "OK" || echo "FAILED"
+		done || echo "NOT FOUND"
+	done
+else
+	DIR=$1 
 	echo -n "CRON: Searching group "$PREFIX$DIR"..." 
 	/usr/bin/getent group $PREFIX$DIR > /dev/null && echo "OK" && \
 	for USER in $(/usr/bin/getent group $PREFIX$DIR | awk '{split($1,users,":"); split(users[4],user,","); for (i=1;i in user;i++) {print user[i];}}'); do
@@ -11,4 +24,4 @@ for DIR in $(ls -l $BASE_DIR | awk '{if ($4 != "root"){print $9;}}'); do
 		mkdir -p /home/$USER && chown $USER /home/$USER && \
 		cd /home/$USER && ln -sf $BASE_DIR/$DIR && echo "OK" || echo "FAILED"
 	done || echo "NOT FOUND"
-done
+fi
