Update userlinks

diff --git a/sssd/assets/userlinks b/sssd/assets/userlinks
--- a/sssd/assets/userlinks
+++ b/sssd/assets/userlinks
@@ -8,8 +8,8 @@ for DIR in $(ls -l $BASE_DIR | awk '{if ($4 != "root"){print $9;}}'); do
 	/usr/bin/getent group $PREFIX$DIR > /dev/null && \
 	for USER in $(/usr/bin/getent group $PREFIX$DIR | awk '{split($1,users,":"); split(users[4],user,","); for (i=1;i in user;i++) {print user[i];}}'); do
 		echo "OK"
-		echo "      Adjusting "$USER" link to "$BASE_DIR"/"$DIR"..." && \
+		echo -n "      Adjusting "$USER" link to "$BASE_DIR"/"$DIR"..." && \
 		mkdir -p /home/$USER && chown $USER /home/$USER && \
-		cd /home/$USER && ln -sf $BASE_DIR/$DIR 
+		cd /home/$USER && ln -sf $BASE_DIR/$DIR && echo "OK" || echo "FAILED"
 	done || echo "NOT FOUND"
 done
